# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Release to Marketplace
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        check-latest: true
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Verify with Gradle
      run: ./gradlew test
    - name: Publish to Marketplace
      run: ./gradlew publishPlugin
      env:
        INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
    - name: Create an automatic release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
